chore: setup github action for build number

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -13,6 +13,19 @@ jobs:
         with:
           java-version: "12.x"
       - uses: subosito/flutter-action@v1
+      - name: Check previous build number
+        id: check_build_number
+        run: echo "::set-output name=last_build_number::$(cat build_number.txt)"
+        continue-on-error: true
+      - name: Set current build number
+        id: set_build_number
+        run: echo $(( $(cat build_number.txt) + 1 )) > build_number.txt
+      - name: Compare build numbers
+        run: |
+          if [[ "${{ steps.check_build_number.outputs.last_build_number }}" == "$(cat build_number.txt)" ]]; then
+          echo "Build number has not been updated. Failing the workflow."
+          exit 1
+          fi
       - name: Run flutter clean
         run: flutter clean
       - name: "Run flutter pub get"
